name: flutter_application_1
description: "CraneIQ Pro - Industrial Crane Monitoring"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  syncfusion_flutter_gauges: ^31.2.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  provider: ^6.0.0
  http: ^1.6.0
  mqtt_client: ^10.11.1
  supabase_flutter: ^2.1.2
  postgrest: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  web: ">=1.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/qa_data.json